### ISSUE TITLE
VEX 2 PBF

### ISSUE THREAD

**Issue by muZZkat** [conveyal/osm-lib#5]
Awesome project, very impressed with the speed of extracts. Is there a way PBF export or a VEX2PBF conversion somewhere or am I missing something?

**Comment by abyrd** [comment]
There wasn't for a while, now there is. Just run com.conveyal.osmlib.main.Converter with two arguments: the input file and the output file. The type (pbf or vex) will be detected from the extensions. But you don't need to convert anymore: I added PBF output to osm-lib. So now when you hit the HTTP endpoint you can just make the extension .pbf and you should get PBF.

**Comment by muZZkat** [comment]
Nice. Thanks!
